export { default as Account } from "./account/Account";
export { default as AccountMovie } from "./account/AccountMovie";
export { default as SignIn } from "./form/SignIn";
export { default as SignUp } from "./form/SignUp";
export { default as MovieRow } from "./row/MovieRow";
export { default as Row } from "./row/Row";
export { default as Footer } from "./Footer";
export { default as Main } from "./Main";
export { default as Navbar } from "./Navbar";
